### PR TITLE
resolve race condition around assignment of calculated rates

### PR DESCRIPTION
**Pull request by maplebed**
fixes issue #4

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Hm, what do you think about moving setting `a.haveData = true` into the section where the lock is already obtained in `updateMaps`? Would allow you to remove the locking and setting from the function literal goroutine in `Start`.

**Comment by nathanleclaire** [comment]
Also, just to make sure -- should `a.haveData` be set to `true` even if `a.savedSampleRates` gets cleared due to no traffic in the past `ClearInterval`?

**Comment by nathanleclaire** [comment]
i.e., in this block:

https://github.com/honeycombio/dynsampler-go/blob/d31b5e963df86221df54859a978f0e9b6a3802ca/avgsamplerate.go#L75-L81

it will cause `GetSampleRate` to return always 1 instead of `GoalSampleRate` I think? (Since the key will not be present)

**Comment by maplebed** [comment]
Yes, haveData should always be true past the first interval.  The difference is "I don't know what the incoming rate is, so the GoalSampleRate is a good default choice" vs. "I know there has been no traffic, so a sample rate of 1 is appropriate."

**Comment by nathanleclaire** [comment]
OK sweet! Thanks for the fix. LGTM

Should we set up TravisCI on this repo so the tests will be run?

**Pull request merged**
